import Link from 'next/link'
import { notFound } from 'next/navigation'
import { approveMaintenanceTicketAction, completeMaintenanceTicketAction, updateMaintenanceTicketAction, uploadMaintenanceFileAction } from '@/actions/maintenance'
import { ConfirmButton } from '@/components/ConfirmButton'
import { Feedback } from '@/components/Feedback'
import { requireUser } from '@/lib/auth'
import { signedFileUrl } from '@/lib/storage'

export default async function MaintenanceDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ erro?: string; sucesso?: string }> }) {
  const { id } = await params
  const messages = await searchParams
  const { supabase } = await requireUser()
  const [{ data: ticket }, { data: providers }, { data: categories }] = await Promise.all([
    supabase.from('maintenance_tickets').select('*, units(name), clients(name), expenses(id, description)').eq('id', id).single(),
    supabase.from('profiles').select('id, full_name').eq('is_active', true).in('role', ['manutencao','admin_operacional','superadmin']).order('full_name'),
    supabase.from('financial_categories').select('id, name').eq('type', 'expense').order('name'),
  ])
  if (!ticket) notFound()
  const photoUrls = (await Promise.all((ticket.photo_paths ?? []).map((path: string) => signedFileUrl(supabase, path)))).filter(Boolean) as string[]
  const quoteUrl = await signedFileUrl(supabase, ticket.quote_path)

  return (
    <>
      <header className="pageHeader"><div><p className="eyebrow">MANUTENÇÃO</p><h1>{ticket.title}</h1><p className="muted">{ticket.units?.name} — {ticket.clients?.name}</p></div><Link className="button secondary" href="/manutencoes">Voltar</Link></header>
      <Feedback erro={messages.erro} sucesso={messages.sucesso} />
      <section className="panel"><div className="panelHeader"><h2>Dados do chamado</h2><span className={`badge ${ticket.status === 'concluded' ? 'confirmed' : 'pending'}`}>{ticket.status}</span></div><form action={updateMaintenanceTicketAction} className="formGrid"><input type="hidden" name="id" value={ticket.id} /><label>Problema<input name="title" required defaultValue={ticket.title} /></label><label>Categoria<input name="category" defaultValue={ticket.category ?? ''} /></label><label>Urgência<select name="urgency" defaultValue={ticket.urgency}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="critical">Crítica</option></select></label><label>Responsável<select name="assigned_to" defaultValue={ticket.assigned_to ?? ''}><option value="">Não atribuído</option>{providers?.map((p: any) => <option value={p.id} key={p.id}>{p.full_name}</option>)}</select></label><label>Fornecedor<input name="supplier" defaultValue={ticket.supplier ?? ''} /></label><label>Custo estimado<input type="number" min="0" step="0.01" name="estimated_cost" defaultValue={ticket.estimated_cost ?? ''} /></label><label>Custo aprovado<input type="number" min="0" step="0.01" name="approved_cost" defaultValue={ticket.approved_cost ?? ''} /></label><label>Prazo<input type="date" name="due_date" defaultValue={ticket.due_date ?? ''} /></label><label>Status<select name="status" defaultValue={ticket.status}><option value="identified">Identificada</option><option value="awaiting_quote">Aguardando orçamento</option><option value="awaiting_approval">Aguardando aprovação</option><option value="approved">Aprovada</option><option value="in_progress">Em execução</option><option value="cancelled">Cancelada</option></select></label><label className="span2">Descrição<textarea name="description" rows={4} defaultValue={ticket.description ?? ''} /></label><label className="checkbox"><input type="checkbox" name="blocks_unit" defaultChecked={ticket.blocks_unit} /> Bloquear hospedagens</label><label>Início do bloqueio<input type="date" name="block_start" defaultValue={ticket.block_start ?? ''} /></label><label>Fim do bloqueio<input type="date" name="block_end" defaultValue={ticket.block_end ?? ''} /></label><div className="formActions"><button className="button primary" disabled={ticket.status === 'concluded'}>Salvar chamado</button></div></form></section>
      <section className="twoColumns"><div className="panel"><div className="panelHeader"><h2>Fotos</h2></div><div className="photoGrid">{photoUrls.map((url) => <a href={url} target="_blank" rel="noreferrer" key={url}><img src={url} alt="Manutenção" /></a>)}</div><form action={uploadMaintenanceFileAction} className="inlineForm topGap" encType="multipart/form-data"><input type="hidden" name="id" value={ticket.id} /><input type="hidden" name="kind" value="photo" /><input type="file" name="file" accept="image/*" required /><button className="button secondary">Enviar foto</button></form></div><div className="panel"><div className="panelHeader"><h2>Orçamento</h2></div>{quoteUrl ? <a className="tableLink" href={quoteUrl} target="_blank" rel="noreferrer">Abrir orçamento</a> : <p className="empty">Nenhum orçamento anexado.</p>}<form action={uploadMaintenanceFileAction} className="inlineForm topGap" encType="multipart/form-data"><input type="hidden" name="id" value={ticket.id} /><input type="hidden" name="kind" value="quote" /><input type="file" name="file" accept="image/*,.pdf" required /><button className="button secondary">Enviar orçamento</button></form></div></section>
      {!['concluded', 'cancelled'].includes(ticket.status) && <section className="panel"><div className="panelHeader"><h2>Aprovação</h2></div><form action={approveMaintenanceTicketAction} className="inlineForm"><input type="hidden" name="id" value={ticket.id} /><label>Valor aprovado<input type="number" min="0" step="0.01" name="approved_cost" defaultValue={ticket.approved_cost ?? ticket.estimated_cost ?? 0} /></label><ConfirmButton label="Aprovar orçamento" confirmMessage="Confirma a aprovação do orçamento?" className="button primary" /></form></section>}
      {!['concluded', 'cancelled'].includes(ticket.status) && <section className="panel"><div className="panelHeader"><h2>Concluir e gerar despesa</h2></div><form action={completeMaintenanceTicketAction} className="formGrid"><input type="hidden" name="id" value={ticket.id} /><label>Categoria financeira<select name="category_id" required><option value="">Selecione</option>{categories?.map((c: any) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Custo final<input type="number" min="0" step="0.01" name="final_cost" defaultValue={ticket.approved_cost ?? ticket.estimated_cost ?? 0} /></label><label className="span2">Observações da conclusão<textarea name="completion_notes" rows={3} /></label><div className="formActions"><ConfirmButton label="Concluir manutenção" confirmMessage="A conclusão criará uma despesa e liberará o bloqueio da unidade. Continuar?" className="button primary" /></div></form></section>}
      {ticket.generated_expense_id && <section className="panel"><p>Despesa gerada: <Link className="tableLink" href={`/financeiro/despesas/${ticket.generated_expense_id}`}>abrir lançamento financeiro</Link>.</p></section>}
    </>
  )
}
